# Generated by Django 5.1.4 on 2025-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisocialapp', '0002_post_comment_like_reshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='agrisocialapp.userprofile'),
        ),
    ]
