# Generated by Django 5.1.4 on 2025-04-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisocialapp', '0003_userprofile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
