# Generated by Django 5.1.4 on 2025-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrisocialapp', '0009_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_membership',
            field=models.BooleanField(default=False),
        ),
    ]
